### ISSUE TITLE
PATH_TO_NPM = setting_overrides.get(     'PATH_TO_NODE',     'npm' ) 

### ISSUE THREAD

**Issue by gbozee** [markfinger/django-node#1]
I am using windows but I couldnt get django to find the `npm` binary. after going through the source, `settings.py` I noticed this

    PATH_TO_NPM = setting_overrides.get(
        'PATH_TO_NODE',
        'npm'
    )

shouldn't it be 

    PATH_TO_NPM = setting_overrides.get(
        'PATH_TO_NPM',
        'npm'
    )

**Comment by glifchits** [comment]
:+1: making this update made it work for me

**Comment by markfinger** [comment]
Thanks for the issue report, gbozee.
