### ISSUE TITLE
Allow custom location for node_modules directory

### ISSUE THREAD

**Issue by owais** [markfinger/django-node#20]
It would be nice to let the users choose a different location for node_modules directory instead of node_modules in the source directory. Some times, we install packages globally instead of a virtualenv (like when in docker) so normal users cannot write to /usr/local/lib/python/... 

Also, some times, we might already have a node_modules directory specified for other npm modules used with the product with proper PATHs set.

**Comment by markfinger** [comment]
Yeah, bundling the node_modules into the virtualenv was originally a hack for a single project, but I've kept using it everywhere else. I've had a bunch of people having issues with it though, so it would be good to fix it.

I'm working on a replacement for django-node's server/services, one of the goals is to replace the multitude of node_modules with a centralised one. This would enable you to rely on node's local/global resolve rather the absolute paths currently used.

In the mean time, PRs are more than welcome.

**Comment by owais** [comment]
That would be great. My solution was to symlink my projects node_modules to
django-node's. Works well. It would also be nice if the new service system
can be more transparent. Transparent as in expose the user to node more
directly instead of hiding it behind the curtains.

I found it a little hard to debug when my webpack config was not working.

**Comment by markfinger** [comment]
django-node is now deprecated. It's successor, js-host, uses a much more conventional npm/node setup with a single source root

**Comment by owais** [comment]
Sweet! I'll check it out over one on the next weekends. Thanks!
