### ISSUE TITLE
django_node does not seem to work on Windows

### ISSUE THREAD

**Issue by skiwi2** [markfinger/django-node#21]
We currently have a setup where we have multiple developers some are on Linux and others are on Windows.

On Linux django_node works perfectly, but on Windows it fails.

We get the following trace:

> "C:\Program Files (x86)\JetBrains\PyCharm 4.0.6\bin\runnerw.exe" C:\Python34\python.exe C:/Users/Frank/Dropbox/PycharmProjects/prototype/manage.py runserver 8000
> Traceback (most recent call last):
>   File "C:/Users/Frank/Dropbox/PycharmProjects/prototype/manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "C:\Python34\lib\site-packages\django\core\management__init__.py", line 338, in execute_from_command_line
>     utility.execute()
>   File "C:\Python34\lib\site-packages\django\core\management__init__.py", line 312, in execute
>     django.setup()
>   File "C:\Python34\lib\site-packages\django__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "C:\Python34\lib\site-packages\django\apps\registry.py", line 108, in populate
>     app_config.import_models(all_models)
>   File "C:\Python34\lib\site-packages\django\apps\config.py", line 198, in import_models
>     self.models_module = import_module(models_module_name)
>   File "C:\Python34\lib\importlib__init__.py", line 109, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1129, in _exec
>   File "<frozen importlib._bootstrap>", line 1471, in exec_module
>   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
>   File "C:\Python34\lib\site-packages\django_node\models.py", line 5, in <module>
>     install_configured_package_dependencies()
>   File "C:\Python34\lib\site-packages\django_node\package_dependent.py", line 19, in install_configured_package_dependencies
>     install_dependencies(directory)
>   File "C:\Python34\lib\site-packages\django_node\package_dependent.py", line 8, in install_dependencies
>     resolve_dependencies(path_to_run_npm_install_in=directory)
>   File "C:\Python34\lib\site-packages\django_node\utils.py", line 223, in resolve_dependencies
>     npm.install(path_to_run_npm_install_in)
>   File "C:\Python34\lib\site-packages\django_node\npm.py", line 37, in install
>     ensure_installed()
>   File "C:\Python34\lib\site-packages\django_node\npm.py", line 16, in ensure_installed
>     raise_if_dependency_missing(NPM_NAME)
>   File "C:\Python34\lib\site-packages\django_node\utils.py", line 121, in raise_if_dependency_missing
>     raise MissingDependency(error)
> django_node.exceptions.MissingDependency: NPM is not installed or cannot be found at path "npm".

NPM is installed and available in the Windows path as `npm --version` works.

**Comment by skiwi2** [comment]
We managed to get it to work by adding the following to our `settings.py` file:

```
import platform

if platform.system() == "Windows":
    DJANGO_NODE["PATH_TO_NPM"] = "npm.cmd"
```

The Node.js version was the newest version from the Node.js website.

**Comment by markfinger** [comment]
Closing this as django-node's been deprecated.

The upstream packages have all been ported over to using a replacement. Unfortunately, said replacement has identified issues on windows systems. See: markfinger/js-host#7
